volumes:
  pglocal:
  redislocal:

services:
  migrator-local:
    build:
      dockerfile: ./migration_local.Dockerfile
    depends_on:
      pg-local:
        condition: service_healthy
    env_file:
      - ./local.env

  pg-local:
    image: postgres
    env_file:
      - ./local.env
    ports:
      - "54321:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pglocal:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6380:6379"
    volumes:
      - redislocal:/data
