package errs

import "errors"

var (
	ErrNotFound           = errors.New("not found")
	ErrInvalidInput       = errors.New("invalid input")
	ErrDatabaseError      = errors.New("database error")
	ErrCommitTransaction  = errors.New("failed to commit transaction")
	ErrNoRows             = errors.New("no rows affected")
	ErrBeginTransaction   = errors.New("failed to begin transaction")
	ErrQueryRowScan       = errors.New("failed to scan query result")
	ErrCreateQuery        = errors.New("failed to create query")
	ErrExec               = errors.New("failed to execute query")
	ErrCreateMember       = errors.New("failed to create member")
	ErrCreateChat         = errors.New("failed to create chat")
	ErrDeleteChat         = errors.New("failed to delete chat")
	ErrSendMessage        = errors.New("failed to send message")
	ErrConnectToDb        = errors.New("failed to connect to database")
	ErrChatNotFound       = errors.New("chat not found")
	ErrMemberNotFound     = errors.New("member not found")
	ErrFailedService      = errors.New("failed with service")
	ErrFailedRepository   = errors.New("failed with repository")
	ErrInvalidPasswords   = errors.New("invalid password")
	ErrNoRowsDelete       = errors.New("no rows to delete")
	ErrNoRowsUpdate       = errors.New("no rows to update")
	ErrCreateUser         = errors.New("failed to create user_v1")
	ErrDeleteUser         = errors.New("failed to delete user_v1")
	ErrGetUser            = errors.New("failed to get user_v1")
	ErrUpdateUser         = errors.New("failed to update user_v1")
	ErrCheckHash          = errors.New("failed to check hashed data")
	ErrConvertRedis       = errors.New("error with convert from redis")
	ErrSaveRedis          = errors.New("failed to save if memeory redis")
	ErrInvalidToken       = errors.New("invalid token")
	ErrMissMatchTokens    = errors.New("miss match tokens")
	ErrNeedAdminRole      = errors.New("access denied need admin role")
	ErrEndpointNotFound   = errors.New("endpoint access not found")
	ErrRedisInternalGet   = errors.New("faild to get user in memory db internal errro")
	ErrFailedUnmarshaling = errors.New("failed to unmarshal data from Redis")
)
